### ISSUE TITLE
doesnt work well with creative worlds

### ISSUE THREAD

**Issue by blurpng** [BlockHorizons/PerWorldInventory#14]
main world - survival
second world - creative

if i go from survival to creative, the inventory stays, if i go back to survival the inventory is gone & the survival inventory isnt restored

using dev-13 on PMMP 3.2.2

**Comment by lukeeey** [comment]
Please download the [latest release](https://github.com/BlockHorizons/PerWorldInventory/releases/tag/v2.0.0), this should work now.
