### ISSUE TITLE
Inventory is getting deleted!

### ISSUE THREAD

**Issue by AlexPads** [BlockHorizons/PerWorldInventory#15]
Players inv is deleted after the server is restarted or after going from creative to surival! 

using dev 13 on pmmp 3.1.4

**Comment by AlexPads** [comment]
Removing MSpawns Fixes this issue !!!!!!!!

**Comment by MistakingManx** [comment]
what if.. the server is highly dependant on MSpawns? Are there any other ways to make this plugin work alongside MSpawns?
