### ISSUE TITLE
Building Terrain almost infinite and Login timeout!

### ISSUE THREAD

**Issue by BrianZP** [BlockHorizons/PerWorldInventory#2]
## Description:
Building terrain wait is too long. And changing world leads to player logging out due to timeout.
## Core:
- [PocketMine-MP](https://github.com/pmmp/PocketMine-MP)
- PerWorldInventory: poggit build [#6](https://poggit.pmmp.io/ci/BlockHorizons/PerWorldInventory/~/dev:6)
## Steps to Reproduce:
- Put the plugin in plugins folder, 
- Configure the worlds you want to have same inventories in,
- Start and join the server,
- There is no building terrain wait,
- After joining put items in your inventory,
- Logout and join the server again,
- There is a long building terrain wait,
- Once successful to login try changing level/world,
- Most probably you will be disconnected due to timeout.
## Crashdumps, errors etc:
- none (even with debug mode set to 3)

**Comment by Sandertv** [comment]
Hmmm... Did you try if the same happens without the plugin? Did it enable correctly?

**Comment by BrianZP** [comment]
Yup I tried entering without the plugin. Everything worked fine. To remove further confusion I tested it with no plugins installed other that PerWorldInventory

**Comment by Sandertv** [comment]
Alright, thanks. I'll be looking into it.

**Comment by Sandertv** [comment]
Could you check if the PerWorldInventory/inventories/yourname.yml file contains text?

**Comment by BrianZP** [comment]
Yes it contains it. And the line is encrypted.

**Comment by Sandertv** [comment]
Okay so saving goes correctly. It must be in the inventory fetching then. Let's see...

**Comment by Sandertv** [comment]
I'm not sure about the long building terrain issue though, I don't think that has to do with this plugin. It doesn't do anything when the player joins after all. I did see that issue reported on the PocketMine repository.

**Comment by Sandertv** [comment]
You could try the latest commit. I'm not sure if that'll work.

**Comment by Sandertv** [comment]
@BrianZP have you tried the latest version? Does your issue still persist?

**Comment by BrianZP** [comment]
Sorry for late reply I was out of country. And I just tested the plugin, the inventory seems to be saving but for some reason whenever a player goes into a different world the inventory is not switched. I will try to explain. So if a player is in world1 and has 2 sticks + 10 gapples and goes into world2 via /warp world2 the inventory is not switched and the player has same inventory in both worlds. But if the player does /clearinventory in world2 and goes back to world1 via /warp world1 the player gets his old inventory back i.e 2 sticks and 10 gapples but once again when the player goes to world2 the player has same inventory.

**Comment by Sandertv** [comment]
Have you added any bundled worlds in the config.yml?

**Comment by BrianZP** [comment]
Nope. I was using the deafult config. Plus none have per-world-inventoy.bypass perm.

**Comment by Sandertv** [comment]
Try the latest version, it should work :)

**Comment by BrianZP** [comment]
Thanks alot @Sandertv everything is working great now!

**Comment by Sandertv** [comment]
Awesome! :)
