### ISSUE TITLE
Inventory dont save when player leaves

### ISSUE THREAD

**Issue by RennoXo** [BlockHorizons/PerWorldInventory#28]
'sry for my bad english'

When the player leaves the server the inventory dont save.

Example:

My server have 2 worlds :
world 1 - Hub
world 2

When the player is in world 2 and leaves the server and then go back to world 2 , the inventory dont saved.

It only saves when the player comes first to the hub and leave the game in the  Hub

**Comment by artur2612** [comment]
!!!
I fixed it myself!

I edited the PlayerQuit event
!!!

**Comment by RennoXo** [comment]
!!!
I fixed it myself!

I edited the PlayerQuit event
!!!
