### ISSUE TITLE
Inventory glitch.

### ISSUE THREAD

**Issue by Enrick3344** [BlockHorizons/PerWorldInventory#3]
When someone is in a world where there is a different inventory and the server restarts, when they will come back their inventory will be the same as the world they were before. in exemple:
Im in Plot World (Has a different Inventory as Others) and the server reboot. I come back on and In my Hub world I have my Plot world inventory. and I lost everything else.
I'm getting that issue!

**Comment by Sandertv** [comment]
Ah, I think I see what your issue is. I assume the server restarts when you're in the plots world, then when you re-join you spawn in the hub world?

**Comment by Enrick3344** [comment]
That was exacly the problem! Thanks for the fix! Will test now

**Comment by Enrick3344** [comment]
Tested! Works Perfectly!

**Comment by Sandertv** [comment]
Awesome, glad to hear.
