### ISSUE TITLE
I cant break blocks and more

### ISSUE THREAD

**Issue by DPG896** [BlockHorizons/PerWorldInventory#35]
I cant place or destroy blocks. Even it doesnt work. Look at this errors
![Screenshot_20210413-054756](https://user-images.githubusercontent.com/82310008/114467278-35567880-9bd9-11eb-9df1-1b8eb958a9a1.png)
![Screenshot_20210413-054800](https://user-images.githubusercontent.com/82310008/114467298-3daeb380-9bd9-11eb-87d0-ebabc04320c2.png)

**Comment by DPG896** [comment]
This issue is still open lol

**Comment by lukeeey** [comment]
You are using [PerWorldPlayer](https://github.com/BlockHorizons/PerWorldPlayer). That is a separate plugin.
